### ISSUE TITLE
Questions from example:simple-api

### ISSUE THREAD

**Issue by camyyssa** [aengl/cocoon-demo#2]
1. Why is there nothing displayed on the graph when I choose any combination other than the default?
<img width="929" alt="Screenshot 2019-08-09 at 21 08 47" src="https://user-images.githubusercontent.com/131612/62803881-f1e66580-baeb-11e9-8c41-bac11616b30c.png">
<img width="1449" alt="Screenshot 2019-08-09 at 21 02 04" src="https://user-images.githubusercontent.com/131612/62803883-f4e15600-baeb-11e9-83ec-aff44b713b25.png">

2. Why does the preview change every time I click on the `MapValues` node?
> You already explained, but I think we might want to add an explanation. The reason was: all preview views will sample the data so it doesn't affect performance

<img width="207" alt="Screenshot 2019-08-09 at 21 07 19" src="https://user-images.githubusercontent.com/131612/62804034-586b8380-baec-11e9-8020-320458e7f58b.png">

3. Why is y the only dimension that has `' '` attached?
<img width="329" alt="Screenshot 2019-08-09 at 21 08 37" src="https://user-images.githubusercontent.com/131612/62804043-5d303780-baec-11e9-898b-41d50770359c.png">

4. Almost missed the fact that there was a readme available for the `simple-api` example. At least for the first example, maybe we should add a link to it in the main readme. It also took me a bit to realize I get a tooltip on mouseover. 

I think I'll suggest adding a separate node under the first one that only does documentation, and describes exactly this: Text underneath `Hover a node to get a snippet of what it does`. Text on hover `Check out the readme for this demo at blablabla/readme.html`

**Comment by camyyssa** [comment]
Could have dug a bit more into these questions myself, but this issue is also for me, not only for you. If anything is left after the first time you see the issue, feel free to close it 🙂

**Comment by aengl** [comment]
Thanks for the feedback!

1. The data isn't very good, data points only contain a single measurement, so they can't be plotted against one another. I switched to another API in eef969b.

2. 45720b398d8363baf515ea880a8be7600f141872 addresses that.

3. `y` is a special [boolean attribute](https://yaml.org/type/bool.html) in YAML. Cocoon has no problem reading it correctly if you skip the quotes, but the `js-yaml` serialiser will add them back.

4. Will address those another day 😁

**Comment by aengl** [comment]
I think with 1f4769d we resolved everything here.
